apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-nginx-ingress
  name: kube-nginx-ingress-prometheus-discovery
  namespace: kube-nginx-ingress
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10254
    protocol: TCP
    targetPort: 10254
  selector:
    app: nginx
