apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-nginx-ingress-bmlb
  name: kube-nginx-ingress-bmlb-prometheus-discovery
  namespace: kube-nginx-ingress
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10255
    protocol: TCP
    targetPort: 10255
  selector:
    app: bmlb
