apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-ingress
  annotations:
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: basic-auth
    ingress.kubernetes.io/auth-realm: "Authentication Required"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - ##PROMETHEUS_HOST##
    secretName: prometheus-tls
  rules:
  - host: ##PROMETHEUS_HOST##
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus-k8s
          servicePort: web
